config/routes.rb
Rails.application.routes.draw do
  resources :tweets, :golden_globe_tweets, :oscar_tweets

   root 'golden_globe_tweets#index'

end

app/models/oscar_tweet.rb
class OscarTweet

	include Mongoid::Document
	field :id, type: Integer
	field :text, type: String
	field :user_id, type: Integer
	field :emotion, type: String
	field :created_at, type: Time
	field :lang, type: String

	def self.emotion_count
		map = %Q{
			function() {
				emit(this.emotion, {count: 1})
			}
		}

		reduce = %Q{
			function(key, values){
				var result = {count: 0}
				values.forEach(function(value){
					result.count += value.count;
				});
				return result; 

			}
		}	
	

		Hash[self.map_reduce(map, reduce).out(inline: true).collect {|v| [v["_id"], v["value"]["count"].to_i]  }]
			
	end



	def self.daily_emotion_count(ratio=false, percent = true,dcjs_format = true)
		map = %Q{
			function() {
				emit([this.created_at.toLocaleDateString(),this.emotion], {count: 1})
			}
		}

		reduce = %Q{
			function(key, values){
				var result = {count: 0}
				values.forEach(function(value){
					result.count += value.count;
				});
				return result; 

			}
		}	
		result = {}
		sum_by_day = {}
		dcjs_result = [] if dcjs_format
		self.map_reduce(map, reduce).out(inline: true).each do |v|
			date = Date.parse(v['_id'][0])
			emotion = v['_id'][1]
			count = v['value']["count"].to_i

			if result.has_key? date
				result[date][emotion] = count
				sum_by_day[date] += count
			else
				result[date] = {emotion => count}
				sum_by_day[date] = count.to_f
			end
			dcjs_result.push({date: date.to_s, emotion: emotion, count: count}) if dcjs_format
		
		end
		
		if ratio
			dcjs_result = [] if dcjs_format
			result.each do |date, emotions|
				emotions.each do |emotion,count|
					result[date][emotion] /= sum_by_day[date]
					result[date][emotion] *= 100 if percent
					dcjs_result.push({date:date.to_s, emotion: emotion, count: result[date][emotion]}) if dcjs_format
				end
			end
		end

		dcjs_format ? dcjs_result : result


	end



	



end

app/controllers/oscar_tweets_controller.rb
class OscarTweetsController < ApplicationController

	def index
		if params[:q].present? 
			@tweets = gon.daily_emotion  = OscarTweet.where(:text => /#{params[:q]}/i)
			
		else
			@tweets = OscarTweet
			
		end

		if params[:user].present? and params[:user][:born_on].present?
			@date = Time.parse params[:user][:born_on]
		else
			@date = Time.new(2015,2,22)
		end

		gon.daily_emotion = @tweets.daily_emotion_count
		gon.daily_emotion_before = @tweets.where(:created_at => {:$lt => @date}).daily_emotion_count
		gon.daily_emotion_after = @tweets.where(:created_at => {:$gte => @date}).daily_emotion_count
		@q = @date
	end

end

app/helpers/oscar_tweets_helper.rb
module OscarTweetsHelper
end

app/views/oscar_tweets/index.html.erb
<div class="row-fluid">
	<div class="col-md-8">
		<h1>Oscar Twitter Visualization</h1>
		<h2>The 2015 Oscars was awarded in 22nd Feb</h2>
		<%= form_tag(oscar_tweets_path, :method => :get) do %>
 	<div class="form-group">
		<%= label_tag(:q, "Search for:") %>
		<%= text_field_tag(:q) %>
	</div>
	<div class="form-group">
		<%= label_tag(:user, "Select partition date ") %>
		<%= date_field(:user, :born_on) %>
	</div>
	<%= submit_tag("Search", :class => "btn btn-primary") %>
<% end %>

	</div>
	<div class="col-md-3">
		<%=image_tag("oscars.jpg", :size => "300x200")%>
	</div>
</div>



<div id = "line-chart"></div>
<div class="row-fluid">
	<div class="col-md-4">
		<h3>Overall</h3>
		<div id = "pie-chart"></div>
	</div>
	<div class="col-md-4">
		<h3>Before <%=@date.to_date.to_s%></h3>
		<div id = "pie-chart-before"></div>
	</div>
	<div class="col-md-4">
		<h3>After <%=@date.to_date.to_s%></h3>
		<div id = "pie-chart-after"></div>
	</div>
</div>